# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ProfileUpdate

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '30 5,17 * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
    - run: npm install
    - run: |
          npm run profile-update
      env: 
        API_KEY: ${{ secrets.API_KEY }}
    - run: |
          git config user.name frcofilippi
          git config user.email frcofilippi@gmail.com
          git add .
          git commit -m "[ACTION] - Commited updates to profile page"
          git push
